name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build
        run: dotnet build --no-restore
      
      - name: Test with coverage
        run: |
          dotnet test --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutput=TestResults/ /p:CoverletOutputFormat=opencover
      
      - name: Generate Coverage Badge
        uses: simon-k/dotnet-code-coverage-badge@v1.0.0
        with:
          label: 'Coverage'
          color: 'brightgreen'
          path: '/home/runner/work/PEengineersCAN/PEengineersCAN/PEengineersCAN.Tests/TestResults/coverage.opencover.xml'
          gist-filename: 'code-coverage.json'
          gist-id: 'b0e41f803bb07bbbfaeb69d3de741def'
          gist-auth-token: ${{ secrets.GIST_AUTH_TOKEN }}
